---
# OUTBOUND
# komodo_core_address: "wss://komodo.{{ public_domain }}"
# komodo_core_public_key is supplied by Semaphore as a normal Extra Variable.

# INBOUND
komodo_server_enabled: true
komodo_core_http_address: "https://komodo.{{ public_domain }}"
komodo_core_api_key: >-
  {{
    lookup(
      'ansible.builtin.env',
      'KOMODO_CORE_API_KEY',
      default=undef()
    )
  }}
komodo_core_api_secret: >-
  {{
    lookup(
      'ansible.builtin.env',
      'KOMODO_CORE_API_SECRET',
      default=undef()
    )
  }}
enable_server_management: true
# generate_server_passkey: false
server_name: >-
  {{
    (ansible_host | default(inventory_hostname))
    if 'lxc' in group_names
    else inventory_hostname
  }}
server_address: >-
  {{
    (komodo_ssl_enabled | ternary('https', 'http'))
    ~ '://' ~ ansible_host ~ ':' ~ komodo_periphery_port
  }}

allow_overwrite_key_files: true

komodo_registry_providers:
  - domain: "dhi.io"
    accounts:
      - username: >-
          {{
            lookup(
              'ansible.builtin.env',
              'KOMODO_REGISTRY_USERNAME',
              default=undef()
            )
          }}
        token: >-
          {{
            lookup(
              'ansible.builtin.env',
              'KOMODO_REGISTRY_TOKEN',
              default=undef()
            )
          }}
