---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: >-
      geerlingguy/docker-debian12-ansible:latest@sha256:166fab85a8444ec6c9eeb1eaefd7fe4d064514482d3d876fc96da4aca370ecfc
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: ansible
