---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: io
    image: geerlingguy/docker-debian12-ansible@sha256:a131e3b7a9a38dda40e98b49b39d6200ffab0ad853c714a513f5eea41bab9a25
    pre_build_image: true
    pull: true
    privileged: true
    cgroupns_mode: host
    command: >-
      /bin/sh -c 'if ! mountpoint -q /proc/sys/fs/binfmt_misc; then
      mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc; fi &&
      mount --bind /proc/sys/fs/binfmt_misc/status
      /proc/sys/fs/binfmt_misc/status &&
      mount -o remount,bind,ro /proc/sys/fs/binfmt_misc/status &&
      exec /lib/systemd/systemd'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: europa
    image: geerlingguy/docker-debian12-ansible@sha256:a131e3b7a9a38dda40e98b49b39d6200ffab0ad853c714a513f5eea41bab9a25
    pre_build_image: true
    pull: true
    privileged: true
    cgroupns_mode: host
    command: >-
      /bin/sh -c 'if ! mountpoint -q /proc/sys/fs/binfmt_misc; then
      mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc; fi &&
      mount --bind /proc/sys/fs/binfmt_misc/status
      /proc/sys/fs/binfmt_misc/status &&
      mount -o remount,bind,ro /proc/sys/fs/binfmt_misc/status &&
      exec /lib/systemd/systemd'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: ansible
