---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible@sha256:2effe5239c105630a302ec605f5d7df9e72a8894a0186a8dcec824d366abbff1
    pre_build_image: true
    pull: true
provisioner:
  name: ansible
verifier:
  name: ansible
