---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible@sha256:ebe72ccb840fca0880e3a0c07cd6f5dec9f7ce85de008c8d9a51c3c87c0b2091
    pre_build_image: true
    pull: true
provisioner:
  name: ansible
verifier:
  name: ansible
