---
galaxy_info:
  author: emanuelsipos
  description: Configure compressed RAM swap via systemd-zram-generator
  license: MIT
  min_ansible_version: "2.21"
  platforms:
    - name: Debian
      versions:
        - bookworm
collections:
  - ansible.posix
dependencies: []
