---
- name: Install and configure Tailscale
  hosts: "{{ limit | default('machines') }}"
  tags: [tailscale]
  vars_files:
    - ../../vars/tailscale.yml

  roles:
    - role: artis3n.tailscale.machine
      tags: [tailscale]
