---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible@sha256:324494545c4da6fd1604c3fd702840a37242410254950d855199a4a540e592cf
    pre_build_image: true
    pull: true
provisioner:
  name: ansible
verifier:
  name: ansible
