---
- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: _zram_container_check.rc | default(0) != 0

- name: Restart zram swap devices
  ansible.builtin.systemd_service:
    name: "dev-{{ item }}.swap"
    state: restarted
  loop: "{{ zram_devices.keys() | list }}"
  when: _zram_container_check.rc | default(0) != 0
