---
- name: Install and configure a Beszel binary agent with public key.
  hosts: "{{ limit | default('all') }}"
  tags: [beszel]
  vars_files:
    - ../vars/beszel.yml

  pre_tasks:
    - name: Validate Beszel configuration
      ansible.builtin.assert:
        that:
          - agent_public_key is defined
          - agent_public_key | length > 0
          - public_domain is defined
          - public_domain | length > 0
          - public_domain is match('^[A-Za-z0-9.-]+$')
        quiet: true
        fail_msg: Missing or invalid Beszel configuration from Semaphore
      no_log: true
      tags: [always]

  roles:
    - role: community.beszel.agent
      tags: [beszel, agent]
