---
- name: Install and configure a Beszel binary agent with public key.
  hosts: "{{ limit | default('all') }}"
  tags: [beszel]
  vars_files:
    - ../vars/beszel.yml

  roles:
    - role: community.beszel.agent
      tags: [beszel, agent]
