---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: io
    image: geerlingguy/docker-debian12-ansible@sha256:f3afc780f893fed63dcd90e2ee14e46d3c8d003940ffaff77015eb88b9606f91
    pre_build_image: true
    pull: true
    privileged: true
    cgroupns_mode: host
    command: >-
      /bin/sh -c 'if ! mountpoint -q /proc/sys/fs/binfmt_misc; then
      mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc; fi &&
      mount --bind /proc/sys/fs/binfmt_misc/status
      /proc/sys/fs/binfmt_misc/status &&
      mount -o remount,bind,ro /proc/sys/fs/binfmt_misc/status &&
      exec /lib/systemd/systemd'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: ansible
